name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Pytest
      run: poetry run python -m pytest

    - name: Ruff
      run: poetry run ruff check --output-format=github .

    - name: Check types with mypy
      run: poetry run mypy src

    - name: Bandit
      run: poetry run bandit -r src -c pyproject.toml
